Repository Solvro/mobile-wakacyjne-wyzwanie-2025, pull requests merged in 2025-08, with the labels that each got.

#5 feat: add lista 3
  lista_3/README.md
Labels: size/M

#15 1-Dominik-Kaczmarek
  where_to_go/.gitignore
  where_to_go/android/gradle/wrapper/gradle-wrapper.properties
  where_to_go/android/settings.gradle
  where_to_go/assets/images/cape-town-view.jpg
  where_to_go/assets/images/kyoto-view.jpg
  where_to_go/assets/images/paris-view.jpg
  where_to_go/assets/images/reykjavik-view.jpg
  where_to_go/assets/images/rio-view.jpg
  where_to_go/assets/images/sydney-view.jpg
  where_to_go/assets/images/zermatt-view.jpg
  where_to_go/lib/dream_place_screen.dart
  where_to_go/lib/main.dart
  where_to_go/macos/Flutter/GeneratedPluginRegistrant.swift
  where_to_go/pubspec.lock
  where_to_go/pubspec.yaml
Labels: size/XL, verified

#33 2-Dominik-Kaczmarek
  .github/workflows/flutter_ci.yaml
  README.md
  lista_2/lista_2.md
  lista_3/README.md
  where_to_go/.gitignore
  where_to_go/lib/app_router.dart
  where_to_go/lib/details_screen.dart
  where_to_go/lib/dream_place_screen.dart
  where_to_go/lib/favorites_screen.dart
  where_to_go/lib/features/favorite/favorite_places_provider.dart
  where_to_go/lib/features/favorite/favorite_provider.dart
  where_to_go/lib/features/places/place_details_provider.dart
  where_to_go/lib/features/places/places_provider.dart
  where_to_go/lib/main.dart
  where_to_go/lib/place.dart
  where_to_go/lib/places_list.dart
  where_to_go/pubspec.lock
  where_to_go/pubspec.yaml
Labels: size/XXL, verified

#47 2-wojciech-dominiak
  where_to_go/.gitignore
  where_to_go/lib/app_router.dart
  where_to_go/lib/dream_place_list.dart
  where_to_go/lib/dream_place_screen.dart
  where_to_go/lib/features/favorite/favorite_provider.dart
  where_to_go/lib/features/places/place.dart
  where_to_go/lib/features/places/places_provider.dart
  where_to_go/lib/main.dart
  where_to_go/lib/place.dart
  where_to_go/pubspec.lock
  where_to_go/pubspec.yaml
Labels: size/L, verified
